### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by perborgen** [dwyl/hapi-auth-github#11]
In step 3, the step-by-step link is suppose to be the same as the one in step 2, right?
Currently, its broken, as GIITHUB has been swapped with GOOGLE. 

**
3. Export the Required Environment Variables

Once you've created your app following the GOOGLE-APP-STEP-BY-STEP-GUIDE <---- (broken link)

**Comment by nelsonic** [comment]
Hi @perborgen! Thanks _very much_ for reporting this.  :+1: 
My "[tidy up](https://github.com/dwyl/hapi-auth-github/pull/10)" Pull Request fixes the typos... :memo: 
You have write-access to this repo so please review & merge the PR to confirm its fixed. thanks!
