### ISSUE TITLE
Store the redirect url as an Environment Variable?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-github#14]
In keeping with 12 Factor App Config guidelines: http://12factor.net/config should we store **_all**_ config in the environment...?

**Comment by jrans** [comment]
@nelsonic Was about to create this issue myself! Will fix.

Goes hand in hand with base url and token info and seems very strange to separate. Can't think of any extra benefits of it is as it is. Changing.

**Comment by nelsonic** [comment]
Changing this from a _hard-coded_ value to an environment(al) value is _desirable_ but it means we will introduce a _breaking change_ where existing users of this plugin (_it's being downloaded by someone..._) https://www.npmjs.com/package/hapi-auth-github  will need to be informed that they _need_ to set the `GITHUB_AUTH_REDIRECT_URL` ... 
FYI calling it _simply_ `REDIRECT_URL` will _conflict **somewhere**_ so we need to be specific with the name. :wink:
