### ISSUE TITLE
Update (devDependencies) and improve readme where possible

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-github#17]
Sadly, the `devDependencies` have aged on this ... https://david-dm.org/dwyl/hapi-auth-github?type=dev

![hapi-auth-github-devdependencies](https://cloud.githubusercontent.com/assets/194400/19173517/a26eb38e-8c1f-11e6-80c9-7fd243d4839d.png)

We need a _quick_ PR to update them. _and_... if you spot anything unclear in the Readme/Instructions, _please_ update/improve. (_thanks!_)

Why is `codecov` badge "unknown"...? can you please investigate? 😕 
We _prefer_ to use the shields.io version in any case. see the table: https://github.com/dwyl/technology-stack#open-source-projects-we-use

> note: after that we will `also` need to update: https://github.com/nelsonic/hapi-auth-github-example ...

**Comment by jrans** [comment]
#18 #20 created in relation

**Comment by jrans** [comment]
@nelsonic having problem just visiting https://david-dm.org/ right now so leaving dependencies for now..

**Comment by nelsonic** [comment]
@jrans looks like David-DM is "up" again... 😉
