### ISSUE TITLE
Let user override GitHub URL

### ISSUE THREAD

**Issue by pdziok** [dwyl/hapi-auth-github#31]
I'm currently using GitHub Enterprise which is hosted on a different host than github.com.

I'd like to be able to override hosts that are currently hardcoded but keep default value if nothing is provided.

**Comment by iteles** [comment]
@pdziok Sounds like a great addition! If you have a chance to submit a PR, please do ✨

**Comment by pdziok** [comment]
I can sure do. Would you rather like it [configured using envs (as other params)](https://github.com/dwyl/hapi-auth-github#3-export-the-required-environment-variables) or [should I specify it in options next to handler](https://github.com/dwyl/hapi-auth-github#5-register-the-plugin-into-your-hapijs-server)?

**Comment by iteles** [comment]
@pdziok Hooray! 🎉 
Environment variables would be perfect for this, thanks. 👍

**Comment by pdziok** [comment]
It took me some time but finally made it. Please have a look at PR and think what can we do in order to make it pass the tests 🙇

**Comment by nelsonic** [comment]
@pdziok `hapi-auth-github@2.1.0` is now available on NPM with your changes. thanks again. 👍
