### ISSUE TITLE
Add Simple Example?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-github#5]
Is it enough to point people towards **_Tudo**_ or do people want a _simpler_ example?

**Comment by nelsonic** [comment]
Something simple: https://github.com/nelsonic/hapi-auth-github-example

**Comment by jrans** [comment]
@nelsonic dwyl/labels will be a good place to send when done! Will document when ready 👍

**Comment by nelsonic** [comment]
@jrans _totally agree_! 😉

**Comment by nelsonic** [comment]
https://github.com/dwyl/labels/
